name: 'Setup Amp CLI'
description: 'Install and configure Sourcegraph Amp CLI with Bun package manager'
author: 'ben-ranford'

branding:
  icon: 'terminal'
  color: 'orange'

inputs:
  version:
    description: 'Amp CLI version to install'
    required: false
    default: 'latest'
  
  bun-version:
    description: 'Bun version to install if not present'
    required: false
    default: 'latest'
  
  amp-api-key:
    description: 'Amp API key for authentication'
    required: false
  
  prompt:
    description: 'Initial prompt to send to Amp CLI after setup (for prompt ingestion)'
    required: false

outputs:
  amp-version:
    description: 'Installed Amp CLI version'
    value: ${{ steps.install.outputs.amp-version }}
  
  amp-path:
    description: 'Path to Amp CLI executable'
    value: ${{ steps.install.outputs.amp-path }}
  
  bun-version:
    description: 'Installed Bun version'
    value: ${{ steps.install.outputs.bun-version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Amp CLI
      id: install
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          pwsh -File "${{ github.action_path }}/scripts/install.ps1" \
            -Version "${{ inputs.version }}" \
            -BunVersion "${{ inputs.bun-version }}" \
            -Prompt "${{ inputs.prompt }}"
        else
          bash "${{ github.action_path }}/scripts/install.sh" \
            "${{ inputs.version }}" \
            "${{ inputs.bun-version }}" \
            "${{ inputs.prompt }}"
        fi
      env:
        Amp_API_KEY: ${{ inputs.amp-api-key }}
    
    - name: Validate Installation
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          pwsh -File "${{ github.action_path }}/scripts/validate.ps1"
        else
          bash "${{ github.action_path }}/scripts/validate.sh"
        fi
