name: ❓ Question or Help
description: Ask a question about using the Setup Amp CLI Action
title: "[Question]: "
labels: ["question", "help-wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about using the Setup Amp CLI Action? Please provide as much context as possible so we can help you effectively.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to accomplish? What have you tried so far?
      placeholder: |
        I'm trying to...
        I've already tried...
    validations:
      required: true

  - type: dropdown
    id: runner-os
    attributes:
      label: Runner Operating System
      description: Which OS are you using (if relevant)?
      options:
        - ubuntu-latest
        - ubuntu-20.04
        - ubuntu-22.04
        - macos-latest
        - macos-11
        - macos-12
        - macos-13
        - windows-latest
        - windows-2019
        - windows-2022
        - Self-hosted runner
        - Not applicable
        - Other (please specify below)

  - type: textarea
    id: current-workflow
    attributes:
      label: Current Workflow Configuration
      description: Share your current workflow setup (if relevant)
      render: yaml
      placeholder: |
        - name: Setup Amp CLI
          uses: ben-ranford/setup-ampcli-action@v1
          with:
            # ... your current configuration

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages or Logs
      description: If you're getting errors, please paste them here
      render: text
      placeholder: Paste any error messages here...

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details that might be helpful
      placeholder: Any additional context...

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have checked the README and documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true